//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lucha.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestauranteEntities2 : DbContext
    {
        public RestauranteEntities2()
            : base("name=RestauranteEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DBS> DBS { get; set; }
        public virtual DbSet<DetalleBoleta> DetalleBoleta { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<ModoDePago> ModoDePago { get; set; }
        public virtual DbSet<Pedido> Pedido { get; set; }
        public virtual DbSet<PPS> PPS { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Productos_Pedidos> Productos_Pedidos { get; set; }
        public virtual DbSet<PS> PS { get; set; }
        public virtual DbSet<TipoEmpleado> TipoEmpleado { get; set; }
        public virtual DbSet<TipoProducto> TipoProducto { get; set; }
        public virtual DbSet<User_group> User_group { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
