//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lucha.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos_Pedidos
    {
        public int ID { get; set; }
        public int IdPedido { get; set; }
        public Nullable<int> IDPRod { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
