//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lucha.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_group
    {
        public int idUser_group { get; set; }
        public Nullable<int> idGroup { get; set; }
        public Nullable<decimal> idUser { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Users Users { get; set; }
    }
}
